---
title: 'Příspěvek na MME 2023'
abstract: 
  'Abstract text goes here. This template provides necessary styles and examples to produce valid paper for the international conference on Mathematical Methods in Economics organized by Czech Society for Operations Research and collaborating institutions. The submitted paper cannot be longer than six pages including results, figures and references.'
keywords: 
  'zničit krtka, Talpa, Miller'
JEL:
    'zde budiž jel klasifikace'
AMS:
    'zde budiž ams klasifikace'
author: 'Jindra Lacko'
affiliation: 'Vysoká škola ekonomická v Praze / Katedra Ekonometrie'
email: 'jindra.lacko@vse.cz'
format: 
  pdf:
    keep-tex: true
knitr:
  opts_chunk: 
    fig.showtext: true
execute: 
  eval: true
  echo: false
  message: false
  warning: false
template:
  'template_mme2020.tex'
bibliography:
  'references.bib'
csl: 
  'ieee.csl'
---

# Introduction

Reducing CO~2~ emissions significantly in comparison to 1990 levels is a target of both global @paris16  and regional initiatives @green_deal19. A key factor for achieving this aim is reducing the volume of CO~2~ emissions from transportation @proposal21. This is in line with the contribution transportation related emissions have made to the current stock of CO~2~ in the Earth's atmosphere @cwatch_dex.

In order to achieve these aims it will be necessary to significantly reduce the volume of active Interal Combustion Engine (ICE) vehicles on EU roads. While alternatives to personal vehicle ownership such as mass transit and bicycling are certain to be a part of the solution it is unlikely that the current level of vehicle ownership (over 6 million personal vehicles are registered in the Czech Republic alone, a country of 10 million inhabitants @slaba_houst22) could be feasibly reduced to zero.

As a consequence any plan to reduce and / or eliminate ICE personal vehicle ownership and use must include introducing of alternatives, such as Electric Vehicles (EV's).

# Literature review 

# Methodology

```{r init}
#| echo: FALSE
#| eval: TRUE

# fce na pěkná procenta
prettyprc <- function(x) {
  res <- (100 * x) %>%
    round(2) %>%
    format(scientific = F, nsmall = 2) %>%
    paste0("%")

  res
}

library(dplyr)
library(dbplyr)
library(tidyr)
library(ggplot2)

con <- DBI::dbConnect(RSQLite::SQLite(), "~/Documents/elektroauta/data/auta.sqlite") # připojit databázi

registrace <- tbl(con, 'registrace_pracovni') %>% 
  # osobáky, bez firem a leasingu
  filter(typ_obchodu == 'retail' & kategorie == "M1") %>% 
  filter(rok_registrace >= '2018' & rok_registrace <= '2022') %>% 
  group_by(rok_registrace, KOD_ORP, typ) %>% 
  summarise(pocet = count(vin)) %>% 
  collect() %>% 
  pivot_wider(names_from = typ, values_from = pocet, values_fill = 0) %>% 
  mutate(pct_spalovaci = spalovací / (spalovací + elektro + hybrid)) %>% 
  mutate(pct_friendly = 1 - pct_spalovaci) %>% 
  ungroup()

DBI::dbDisconnect(con) # poslední zhasne...

rocne <- registrace %>% 
  group_by(rok_registrace) %>% 
  summarise(
    spalovaci = sum(spalovací),
    elektro = sum(elektro),
    hybrid = sum(hybrid),
    celkem = spalovaci + elektro + hybrid,
    podil_elektro = elektro / celkem,
    podil_hybrid = hybrid / celkem,
    podil_ev = podil_elektro + podil_hybrid
            )

```

The data were collected from the Czech Ministry of Transport Open Data @registr monthly snapshots. For the purpose of our analysis the only registrations from years `r min(rocne$rok_registrace)` to `r max(rocne$rok_registrace)` were used. 

In order to focus on end consumer activity we considered only personal vehicles (category M1) registered by natural persons. While electrification of corporate fleets is expected to contribute to the overall reduciton of transport CO~2~ emissions the behaviour of corporate fleets and vehicles under leasing contracts is difficult to model based on local socioeconomic variables. Reasons for this difficulty include the practice of corporate registrations being filed in the municipality of company registration.

During the period in question total of `r prettyNum(sum(rocne$spalovaci) + sum(rocne$elektro) + sum(rocne$hybrid),  big.mark = " ")` retail personal vehicles were registered, of which `r prettyNum(sum(rocne$elektro) + sum(rocne$hybrid), big.mark = " ")` could be considered EV's (`r prettyNum(sum(rocne$elektro),  big.mark = " ")` battery operated EVs and `r prettyNum(sum(rocne$hybrid),  big.mark = " ")` hybrid EVs).

The share of EVs over total retail personal vehicles ranged from `r prettyprc(min(rocne$podil_ev))` in `r rocne$rok_registrace[which.min(rocne$podil_ev)]` `r prettyprc(max(rocne$podil_ev))` in `r rocne$rok_registrace[which.max(rocne$podil_ev)]`.


# Result 

# Discussion

# Conclusion

# References
